language: node_js

services:
  - docker

before_install:
  - docker build /home/travis/build/scrum-gang/neutralinojs/ -t test

node_js:
  - lts/*
  - node

cache: npm

script:
  - cd neutralino.js
  - npm install
  - npm test
  - docker run test
