language: node_js

services:
  - docker

before_install:
  - docker build . -t neutralinojs:test-build

node_js:
  - lts/*
  - node

cache: npm

script:
  - cd neutralino.js
  - npm install
  - npm test
  - docker run neutralinojs:test-build
  - docker ps -a
